PACKAGE_NAME="speakerphone-jieli"
PACKAGE_VERSION="1.0.0"

BUILT_MODULE_NAME[0]="snd-usb-audio"
BUILT_MODULE_NAME[1]="snd-usbmidi-lib"
DEST_MODULE_LOCATION[0]="/updates/sound/usb"
DEST_MODULE_LOCATION[1]="/updates/sound/usb"

AUTOINSTALL="yes"
STRIP[0]="yes"
STRIP[1]="yes"

# Prepare patched source before building
PRE_BUILD="src/post_prepare.sh"
